# Generated by Django 2.2.4 on 2019-08-30 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('article_number', models.CharField(max_length=64)),
                ('unit', models.CharField(choices=[('G', 'g'), ('KG', 'Kg'), ('CL', 'cL'), ('ML', 'mL'), ('L', 'L')], default='KG', max_length=2)),
                ('amount', models.IntegerField()),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('rating', models.FloatField()),
                ('time_from', models.SmallIntegerField()),
                ('time_to', models.SmallIntegerField()),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cookbook.FoodCategory')),
                ('ingredients', models.ManyToManyField(to='cookbook.Ingredient')),
            ],
        ),
    ]
